### ISSUE TITLE
How to install on docker

### ISSUE THREAD

**Issue by mcsteevi** [jobe39/volvo2evcc#2]
Hello,

I'm trying to gitclone repository and start docker. Unfortunately I'm not very familiar with docker and when I startup I'm getting error:

app-1  | Traceback (most recent call last):
app-1  |   File "/volvoAAOS2mqtt/./main.py", line 7, in <module>
app-1  |     from flask import Flask, jsonify
app-1  | ModuleNotFoundError: No module named 'flask'
app-1 exited with code 1

I don't understand Information Point 2:
"Enter your settings into settings.json and start volvo2evcc with Python3 (python3 volvo2evcc.py)"

There's no volvo2evcc.py at all or I can't find ? Could you please explain more detailed how to start repository on docker exactly ?

many thanks
Stefan

**Comment by jobe39** [comment]
Add Flask: das ist eine Python Library, die bei dir offensichtlich nicht installiert ist.

Zum zweiten Punkt - ja sorry, das sollte natürlich Main.py heißen.

**Comment by jobe39** [comment]
As written in the reader:

NOTE: Needs to be run with python3. If you get error messages on startup this is typically, because some library is not installed. Check the error message, copy the name of the library and do pip3 install NAME_OF_LIBRARY

**Comment by mcsteevi** [comment]
Vielen Dank, so funktioniert es jetzt
